/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Negocio.GestaoProdutos.Outros;
import Negocio.GestaoProdutos.Produto;
import Negocio.GestaoProdutos.Tecnologia;
import Negocio.GestaoProdutos.Vestuario;
import Negocio.GestaoUtilizadores.Utilizador;
import Negocio.dssBuyer;

/**
 *
 * @author helder
 */
public class NovoProduto extends javax.swing.JFrame {
    
    private dssBuyer dssBuyer;
    private EcraPrincipal ecra;
    private Utilizador utilizador;

    /**
     * Creates new form NovoProduto
     */
    public NovoProduto(EcraPrincipal e, dssBuyer c, Utilizador u) {
        this.ecra = e;
        this.dssBuyer = c;
        this.utilizador = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        preco = new javax.swing.JTextField();
        quantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Titulo:");

        jLabel2.setText("Preco:");

        jLabel3.setText("Quantidade:");

        jLabel4.setText("Descricao:");

        descricao.setColumns(20);
        descricao.setLineWrap(true);
        descricao.setRows(5);
        jScrollPane1.setViewportView(descricao);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoria:");

        categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tecnologia", "Vestuario", "Outros" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(49, 49, 49)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(jLabel3)
                            .add(jLabel2)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(titulo)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(quantidade, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .add(preco))
                                .add(18, 18, 18)
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(categoria, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(titulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(preco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(categoria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(quantidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            validaCampos();
            Produto p = null;
            String tituloV = this.titulo.getText();
            String quantidadeV = this.quantidade.getText();
            String precoV = this.preco.getText();
            String descricaoV = this.descricao.getText();
            String categoriaV = (String) this.categoria.getSelectedItem();
            switch (categoriaV) {
                case "Tecnologia":
                    p = new Tecnologia(tituloV, descricaoV, Integer.parseInt(quantidadeV), Float.parseFloat(precoV), this.utilizador);
                    break;
                case "Vestuario":
                    p = new Vestuario(tituloV, descricaoV, Integer.parseInt(quantidadeV), Float.parseFloat(precoV), this.utilizador);
                    break;
                default:
                    p = new Outros(tituloV, descricaoV, Integer.parseInt(quantidadeV), Float.parseFloat(precoV), this.utilizador);
                    break;
                
            }
            this.dssBuyer.addProduto(p);
            javax.swing.JOptionPane.showMessageDialog(this, "Produto adicionado com sucesso...");
            this.dispose();
        }
        catch (NumberFormatException e) {javax.swing.JOptionPane.showMessageDialog(this, "Formato do preco ou quantidade errados...");}
        catch (Exception e) {javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    public void validaCampos() throws Exception {
        String tituloV = this.titulo.getText();
        String quantidadeV = this.quantidade.getText();
        String precoV = this.preco.getText();
        String descricaoV = this.descricao.getText();
        if (tituloV.equals("") || quantidadeV.equals("") || precoV.equals("") || descricaoV.equals("")) {
            throw new Exception("Tem de preencher todos os campos...");
        }
        Integer.parseInt(quantidadeV);
        Float.parseFloat(precoV);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox categoria;
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
